### ISSUE TITLE
[Submission]: MindsDB Docker Extension

### ISSUE THREAD

**Issue by collabnix** [docker/extensions-submissions#140]
### Docker Hub repository name

ajeetraina/mindsdb-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by collabnix** [comment]
Strange. The command worked perfectly for me locally.

```
docker extension validate ajeetraina/mindsdb-docker-extension:1.0.0
INFO Checked image labels
INFO Checked metadata.json
INFO Checked image tag is semver
INFO Checked image is multiplatform
INFO 🎉 The extension "ajeetraina/mindsdb-docker-extension:1.0.0" passes the validation checks.
INFO If you want to make your extension available in the marketplace, please submit it for publication at https://www.docker.com/products/extensions/submissions/
```

**Comment by Frezzle** [comment]
That is strange; for me locally it shows the same as GitHub Actions:

```
$ docker extension validate ajeetraina/mindsdb-docker-extension:1.0.0
INFO Pulled image                                 
INFO Checked image labels                         
INFO Checked metadata.json                        
INFO Checked image tag is semver                  
INFO Checked image is multiplatform               
ERRO the image for platform "linux/amd64" is not pushed to DockerHub: https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/ 
ERRO The extension "ajeetraina/mindsdb-docker-extension:1.0.0" hasn't passed the checks to be published.
```

It's [only arm64 on Docker Hub](https://hub.docker.com/r/ajeetraina/mindsdb-docker-extension/tags) at the moment:
![Screenshot 2023-12-12 at 09 31 08](https://github.com/docker/extensions-submissions/assets/5685776/f2554a4a-4d74-4886-a2bc-71f58822f008)


So for the time being, if you follow [this doc](https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/) then it shows how to push both linux architectures to Docker Hub. Then try `/validate` again 🤞

**Comment by ajeetraina** [comment]
@Frezzle I just pushed ```ajeetraina/mindsdb-docker-extension:1.0.1``` Docker image that has both Arm64 as well as amd64. Can you please check?

**Comment by ajeetraina** [comment]
@Frezzle I just built a new Mindsdb Extension that includes both Amd64 and Arm64 platform support.

```
docker run --rm mplatform/mquery ajeetraina/mindsdb-docker-extension:1.0.2
Image: ajeetraina/mindsdb-docker-extension:1.0.2 (digest: sha256:239e8b780a6295f9662b0f40875bc0b7f0d10f4bdf4b76c29449d3b3d5f41406)
 * Manifest List: Yes (Image type: application/vnd.oci.image.index.v1+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm64
   - unknown/unknown
   - unknown/unknown
  ```

Can you please check?

**Comment by Frezzle** [comment]
It's now published @ajeetraina, nice work! 🎉 
![Screenshot 2023-12-13 at 10 19 42](https://github.com/docker/extensions-submissions/assets/5685776/81655bdc-0743-46f7-b9df-141f902262a5)

I did notice a few things that may be worth looking into:
- A one-liner that describes the extension would be useful for users seeing your extension on Hub or Desktop marketplace, instead of only `Mindsdb Docker extension` :) Some examples from other extensions:
![Screenshot 2023-12-13 at 10 26 47](https://github.com/docker/extensions-submissions/assets/5685776/6c76a18a-9683-434c-b044-5a21460fd944)

- On first load of the extension (after installing) it takes me a while to see the content; it's grey for 10-30 seconds. I'm not sure why this is, but maybe a loading state would be good, to know that it's not broken but just doing something.
![Screenshot 2023-12-13 at 10 20 10](https://github.com/docker/extensions-submissions/assets/5685776/79ec0a82-29ca-49bb-9d41-77a82f05e2fc)

- The Intercom chat bubble starts on the left but after clicking it it jumps to the right. Should it start on the right and stay there?
![Screenshot 2023-12-13 at 10 21 55](https://github.com/docker/extensions-submissions/assets/5685776/1782ceea-e816-4f30-ba4b-1e6fc43964bd)
![Screenshot 2023-12-13 at 10 21 47](https://github.com/docker/extensions-submissions/assets/5685776/e57c1e60-7ae6-43a5-a6f9-07a6b564f646)

**Comment by ajeetraina** [comment]
@Frezzle I have updated Dockerfile with the following content and pushed it to Docker Hub

```
 FROM alpine
LABEL org.opencontainers.image.title="Mindsdb" \
    org.opencontainers.image.description="Streamline AI development with MindsDB in your Docker environment. Deploy, manage, and scale your AI models seamlessly" \
    org.opencontainers.image.vendor="Ajeet Singh Raina" \
...
```

**Comment by Frezzle** [comment]
> I have updated description under the Dockerfile with the following content and pushed it to Docker Hub

Nice one! Though I think you accidentally undid the two linux architectures; now it's just one again:
![Screenshot 2023-12-13 at 11 05 23](https://github.com/docker/extensions-submissions/assets/5685776/c37e19a4-eb84-4150-b6f0-d6c1575a6a9f)

**Comment by ajeetraina** [comment]
I will get it fixed. Rebuilding it now.
