### ISSUE TITLE
[Submission]: Kong Konnect extension

### ISSUE THREAD

**Issue by kaiarrowood** [docker/extensions-submissions#168]
### Docker Hub repository name

kong/konnect-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi @kaiarrowood,
I'm reaching out because I saw a bug in the login process of the kong Docker Desktop extension: after entering credentials, I can see the device activation code in Desktop and confirming it. Then the web page proposes to go back to Docker Desktop, and instead of redirecting to the extension screen in Desktop, it redirects to the marketplace details page for the extension. 
Apart from this, the login seems to be working fine, if I then manually click again on the extension tab.

It seems from your web login page, you're redirecting to `docker-desktop://dashboard/marketplace?extensionId=xxx` instead of `docker-desktop://dashboard/extension-tab?extensionId=xxx` (please check details in our [docs](https://docs.docker.com/extensions/extensions-sdk/guides/oauth2-flow/#get-the-authorization-code-and-access-token) for extension oauth)

**Comment by kaiarrowood** [comment]
> Hi @kaiarrowood, I'm reaching out because I saw a bug in the login process of the kong Docker Desktop extension: after entering credentials, I can see the device activation code in Desktop and confirming it. Then the web page proposes to go back to Docker Desktop, and instead of redirecting to the extension screen in Desktop, it redirects to the marketplace details page for the extension. Apart from this, the login seems to be working fine, if I then manually click again on the extension tab.
> 
> It seems from your web login page, you're redirecting to `docker-desktop://dashboard/marketplace?extensionId=xxx` instead of `docker-desktop://dashboard/extension-tab?extensionId=xxx` (please check details in our [docs](https://docs.docker.com/extensions/extensions-sdk/guides/oauth2-flow/#get-the-authorization-code-and-access-token) for extension oauth)

@gtardif Thanks for catching this! I'll roll this into the next release. I read through that code but didn't see mention anywhere about the possible `docker-desktop` links I can use. Do you have a listing of links we can use externally to trigger things in Docker Desktop? Another example I was looking for is like how to link to a specific Docker Image using the Docker Desktop Client... I've been all through the API docs but had trouble locating what I was looking for!
