### ISSUE TITLE
[Submission]: KRS (Kubetools Recommendation Service)

### ISSUE THREAD

**Issue by karanveersingh5623** [docker/extensions-submissions#172]
### Docker Hub repository name

kubetoolsca/krs-docker-extension

### Terms of services

- [x] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi @karanveersingh5623, Thx for submitting an extension for Docker Desktop
I just noticed that the icon that appears in the extension marketplace does not display properly, you need to check the docker label `com.docker.desktop.extension.icon` that you set in your Dockerfile (apparently the URL has expired) and provide a valid icon url
You'll need to push a 0.0.2 new image to hub, let me know if you have any question

**Comment by karanveersingh5623** [comment]
@gtardif 
We have updated the image to docker hub with 0.0.2 tag
https://hub.docker.com/layers/kubetoolsca/krs-docker-extension/0.0.2/images/sha256-e56e2e77e135535bb9e639cf09e3a7b6351761f82488b3f1fd9c79a90debfd43?context=repo

Also we have updated the main branch [](https://github.com/kubetoolsca/krs-docker-extension) , [kubetoolsca/krs-docker-extension](https://open.docker.com/extensions/marketplace?extensionId=kubetoolsca/krs-docker-extension&tag=0.0.2)

**Comment by karanveersingh5623** [comment]
@gtardif , is there any update on krs extension,  let me know if more information needed

**Comment by gtardif** [comment]
Hi @karanveersingh5623, I added `/validate` comment in order to re-run validation on the latest extension version. 
It seems you still have a URL pointing to a non valid image

**Comment by karanveersingh5623** [comment]
@gtardif , we have updated the image and validated it with 0.0.3 tag . Please check again

[https://hub.docker.com/layers/kubetoolsca/krs-docker-extension/0.0.3/images/sha256-b908c6af52a7a33dbbc3b3038264fbf3a8849f05ab5cb87adf4a9c92b0edfb39?context=repo)](https://hub.docker.com/layers/kubetoolsca/krs-docker-extension/0.0.3/images/sha256-b908c6af52a7a33dbbc3b3038264fbf3a8849f05ab5cb87adf4a9c92b0edfb39?context=repo)

Also we have updated the main branch , [kubetoolsca/krs-docker-extension](https://open.docker.com/extensions/marketplace?extensionId=kubetoolsca/krs-docker-extension&tag=0.0.2)

**Comment by karanveersingh5623** [comment]
@gtardif , please check the screen , all validation of 0.0.3 image is passing 

![Image](https://github.com/user-attachments/assets/4308e1e2-64ed-4afb-b11b-50e9273be323)

**Comment by gtardif** [comment]
Hi @karanveersingh5623 , maybe you're not using the latest version of Desktop locally, since we recently added the validation of image URLs to ensure images are accessible. 
Looking at the details of your image on [Docker Hub](https://hub.docker.com/layers/kubetoolsca/krs-docker-extension/0.0.3/images/sha256-b908c6af52a7a33dbbc3b3038264fbf3a8849f05ab5cb87adf4a9c92b0edfb39?context=explore), I see the value of the screenshot label, containing 3 screenshots. The [first one](https://raw.githubusercontent.com/kubetoolsca/krs-docker-extension/refs/heads/main/images/image.png) is accessible, but [second](https://github.com/kubetoolsca/krs-docker-extension/blob/main/images/image1.png?raw=true) and [third](https://github.com/kubetoolsca/krs-docker-extension/blob/main/images/image2.png?raw=true) ones give me a 404 (corresponding to the error above)
