### ISSUE TITLE
[Submission]: Faros Community Edition

### ISSUE THREAD

**Issue by thomas-gerber** [docker/extensions-submissions#60]
### Docker Hub repository name

farosai/faros-ce-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by thomas-gerber** [comment]
Hello, 
I ran `docker extension validate -a -s -i farosai/faros-ce-docker-extension` and even `docker extension validate --auto-resolve-tag --errors-only --sdk-compatibility --validate-install-uninstall farosai/faros-ce-docker-extension` successfully locally. It succeeds. The validation here seems to fail after a long while. Maybe the docker spun up is not beefy enough? (we compose several services, see https://github.com/faros-ai/faros-community-edition#%EF%B8%8F-system-components)

**Comment by thomas-gerber** [comment]
@benja-M-1 is there something required on my end right now?

**Comment by gtardif** [comment]
Hi @thomas-gerber, the validation fails here because the output when spinning up the compose stack is too long and hit some buffer limit (because the compose stack is quite large and pulls many images). 
We need to make some changes in our automated validation for this case. Hopefully we should be able to unblock your extension quickly. 
Thanks for your patience :)

**Comment by gtardif** [comment]
Hi @thomas-gerber, we detected that the extension image is not available anymore on Docker hub. Therefore, users cannot install the extension anymore in Docker Desktop. We've removed the extension from the marketplace to avoid bad user experience.

If you make the extension image available again on Docker hub, please open a new submission to add it back to the extension marketplace.
